import logo_zonex from './assets/logo-zonex.png'
import logo_hero from './assets/logo-hero.png'
import bag from './assets/bag.png'
import user from './assets/user.png'
import menu from './assets/hamburger.png'
import arrow_right from './assets/next.png'
import arrow_left from './assets/previous.png'
